export const GameState = {
  MENU: 'MENU',
  LEAD_CAPTURE: 'LEAD_CAPTURE',
  PLAYING: 'PLAYING',
  GAME_OVER: 'GAME_OVER',
  RESULTS: 'RESULTS'
};

export const PowerUpType = {
  DELEGATE: 'DELEGATE',
  SYSTEMISE: 'SYSTEMISE',
  FOCUS_MODE: 'FOCUS_MODE',
  AI_ASSIST: 'AI_ASSIST',
  CHRISTMAS_TRIGGER: 'CHRISTMAS_TRIGGER'
};